### ISSUE TITLE
Question: GetSitemap instead of Sitemap? why?

### ISSUE THREAD

**Issue by OV2012** [wintoncode/Winton.AspNetCore.Seo#27]
Hi,
sorry, if I ask, but I don't understand why the robots.txt contains "GetSitemap: {sitemapUrl}" instead of simply "Sitemap :{sitemapUrl}?
it's about this function in the RobotsTxtFactory:

```
private string CreateSitemapUrl()
{
	string baseUrl = _httpContextAccessor?.HttpContext?.Request?.GetEncodedUrl();
	Url sitemapUrl = (baseUrl ?? string.Empty).Replace(Constants.RobotsUrl, Constants.SitemapUrl);
	return $"GetSitemap: {sitemapUrl}";
}
```

i mean according to specification it should be sitemap:
https://de.wikipedia.org/wiki/Robots_Exclusion_Standard

thanks!

**Comment by Choc13** [comment]
Hi @OV2012,

Thanks for raising this. You are correct, this is a bug. I'll do a patch for both major versions.

Cheers!
