### ISSUE TITLE
Core 3 support please!

### ISSUE THREAD

**Issue by georgiosd** [wintoncode/Winton.AspNetCore.Seo#37]
Routing has changed...

**Comment by Choc13** [comment]
Hi @georgiosd,

Thanks for raising this. 

I am a little busy with some other things right now, but will get around to this eventually. Unless you would like to give it a shot and open a PR?

**Comment by Choc13** [comment]
OK I think I've figured out how to upgrade to support ASP.NET Core 3.0 apps and have a branch I'm currently working on. Hopefully get this merged a released soon.
